### ISSUE TITLE
Использование RemoteWebDriver

### ISSUE THREAD

**Issue by czen** [Kate2017pro/BRS_Test_main#5]
Если не запускать chrome на той же машине, на которой  выполняется код модульных тестов, то создать гибкое окружение для их выполнения будет гораздо легче

[примеры c RemoteWebDriver](https://www.programcreek.com/java-api-examples/?api=org.openqa.selenium.remote.RemoteWebDriver)

Можно сделать фабрику для создания объекта driver, которая из конфиг. файла прочтет, какой драйвер нужен и создаст его:
1. Или задав как раньше путь к *.exe 
2. Или сделав  new RemoteWebDriver(toUrl("<путь к серверу из конфиг. файла>"), DesiredCapabilities.<имя браузера из конфиг. файла>());

Если сделать так, то можно будет запустить [selenium hub](https://github.com/SeleniumHQ/docker-selenium) с каким угодно набором браузеров и не потратить месяц на установку всего комплекта chrome, firefox, selenium и т.п. на выделенном сервере.

**Comment by czen** [comment]
сейчас для отладки тестов на сервере запущены standalone контейнеры c webdriver server и chrome/firefox:

``` bash
docker run -d -P -p 4488:4444 -p 5901:5900 -v /dev/shm:/dev/shm --name selenium_standalone_chrome selenium/standalone-chrome-debug
docker run -d -P -p 4499:4444 -p 5902:5900 -v /dev/shm:/dev/shm --name selenium_standalone_firefox selenium/standalone-firefox-debug
```

управляющая консоль для [chrome](http://grade-dev.mmcs.sfedu.ru:4488/wd/hub/static/resource/hub.html) и [firefox](http://grade-dev.mmcs.sfedu.ru:4499/wd/hub/static/resource/hub.html) позволяет создавать и удалять сессии вручную

![image](https://user-images.githubusercontent.com/18035867/58111405-153efa00-7bfa-11e9-9d49-86cf165f56a5.png)

по адресам http://grade-dev.mmcs.sfedu.ru:5901 (chrome) и http://grade-dev.mmcs.sfedu.ru:5902 (firefox) работают VNC-серверы, к которым можно подключиться любым VNC-клиентом (пароль: secret) и посмотреть, как работают бразуеры.

![image](https://user-images.githubusercontent.com/18035867/58111525-4b7c7980-7bfa-11e9-9cfe-32340d0a322c.png)

**Comment by czen** [comment]
Для управления всем этим есть portainer:

![image](https://user-images.githubusercontent.com/18035867/58111622-7d8ddb80-7bfa-11e9-8a78-55f22f0ed99e.png)

**Comment by czen** [comment]
[более подробный пример использования RemoteWebDriver с selenium-grid](https://www.guru99.com/introduction-to-selenium-grid.html)

**Comment by czen** [comment]
@Kate2017pro  насчет паролей и явок пишите мне на taccessviolation@gmail.com

я сам могу быть не в курсе, какие серверы требуют авторизации, а какие нет.

по умолчанию все пароли  должны быть "secret"

**Comment by Kate2017pro** [comment]
@czen Вы завтра вечером будете? 
Если хотя бы теоритически я догадываюсь, что и как можно тут сделать. Сегодня попробую. Но может неподняться.
То можно я завтра приду для прояснения всего сразу?

**Comment by czen** [comment]
да, вечером буду

**Comment by Kate2017pro** [comment]
Не стартует новая сессия
`Exception in thread "main" org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '3.13.0', revision: '2f0d292', time: '2018-06-25T15:24:21.231Z'
System info: host: 'ADMIN-PC', ip: '192.168.56.1', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '10.0.2'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:569)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:212)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:143)
	at ru.sfedu.grade.App.main(App.java:41)
Caused by: java.io.IOException: unexpected end of stream on Connection{grade-dev.mmcs.sfedu.ru:5901, proxy=DIRECT hostAddress=grade-dev.mmcs.sfedu.ru/195.208.237.216:5901 cipherSuite=none protocol=http/1.1}
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:208)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:105)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:101)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
	... 4 more
Caused by: java.io.EOFException: \n not found: limit=0 content=…
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:237)
	at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:215)
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
	... 24 more`

**Comment by czen** [comment]
наверное неправильный адрес.
адрес для подключения RemoteWebDriver http://grade-dev.mmcs.sfedu.ru:4488/wd/hub
по этому адресу сейчас работает Chrome в standalone контейнере

**Comment by czen** [comment]
теперь все работает, разве что вписывать `private Boolean run_local=true;` везде неудобно

**Comment by Kate2017pro** [comment]
Везде - это где? Оно же должно читаться из файла настроек. 
 Я же не закончила еще внедрять это везде...

**Comment by czen** [comment]
нет, стоп, я имел в виду, что хоть какие-то тесты запускаются. БОльшая часть падает из-за настроек драйвера, но я увидел, что оно на сервере какие-то тесты запустило, поэтому написал.

Запускал проект под Windows.

**Comment by Kate2017pro** [comment]
Да, что-то должно работать. Вроде три пакета должны запуститься, которые меньше всего. Остальные еще не модифицировались.
